# Generated by Django 4.2.2 on 2023-07-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('besant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Mobile',
            new_name='phone',
        ),
    ]
